version: '2.7'

services:
  frontend:
    build: ./frontend
    image: drinkdomainsupporter/frontend
    container_name: frontend
    ports:
      - 8084:80
    depends_on:
      - backend

  backend:
    build: ./backend
    image: drinkdomainsupporter/backend
    container_name: backend
    ports:
      - 8085:8081
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 8086:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./drinks_db.sql:/docker-entrypoint-initdb.d/drinks_db.sql  # Mount SQL file for initialization

volumes:
  db_data:
